import { StyleSheet } from "react-native";

export const groupStyles = StyleSheet.create({
  mainText: {
    fontSize: 25,
    color: "#f8fefe",
    fontWeight: "600",
    marginBottom: 15,
    alignSelf: "center",
    marginLeft: 15,
  },
  personalisedText: {
    fontSize: 25,
    color: "#f8fefe",
    fontWeight: "600",
    marginBottom: 5,
  },
  personalisedSubText: {
    fontSize: 20,
    color: "#f8fefe",
    fontWeight: "600",
    marginBottom: 15,
    textDecorationLine: "underline",
  },
  groupHeader: {
    fontSize: 18,
    color: "#f8fefe",
    marginBottom: 6,
    marginLeft: 35,
  },
    groupHeaderSmallScreen: {
    fontSize: 18,
    color: "#f8fefe",
    marginBottom: 6,
    marginLeft: 10,
  },
  groupBody: {
    fontSize: 17,
    color: "#f8fefe",
    marginBottom: 10,
    marginLeft: 35,
  },
  groupBodySmallScreen: {
    fontSize: 17,
    color: "#f8fefe",
    marginBottom: 10,
    marginLeft: 5,
  },
  groupBoldHeader: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#f8fefe",
    marginBottom: 10,
    marginLeft: 45,
  },
    groupBoldHeaderSmallScreen: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#f8fefe",
    marginBottom: 10,
    marginLeft: 15,
  },
  groupBoldCourse: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#f8fefe",
    marginBottom: 5,
    marginLeft: 45,
  },
  groupRegHeader: {
    fontSize: 15,
    color: "#f8fefe",
    marginBottom: 10,
    marginLeft: 10,
  },
  topHeader: {
    marginTop: "2%",
    width: "75%",
    alignItems: "flex-start",
    alignSelf: "center",
  },
  flexSplit: {
    marginTop: 20,
    flexDirection: "row",
    justifyContent: "space-evenly",
  },
  personalisedCont: {
    width: "45%",
    backgroundColor: "#112230",
    borderRadius: 10,
    borderColor: "#23CFBB",
    borderWidth: 3,
  },
  pricing: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#f8fefe",
    marginBottom: 10,
    marginLeft: 35,
    textDecorationLine: "underline",
  },
    pricingSmallScreen: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#f8fefe",
    marginBottom: 10,
    marginLeft: 10,
    textDecorationLine: "underline",
  },
  nextLine: {
    fontSize: 15,
    color: "#f8fefe",
    marginBottom: 10,
    marginLeft: 40,
  },
  faqQuestions: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#f8fefe",
    marginBottom: 2,
    marginLeft: 40,
  },
    faqQuestionsSmallScreen: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#f8fefe",
    marginBottom: 2,
    marginLeft: 20,
  },
  Bookings: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#f8fefe",
    marginBottom: 5,
    alignSelf: "center",
  },
  BookingsSmallScreen: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#f8fefe",
    marginBottom: 5,
    alignSelf: "center",
  },
  faqAnswers: {
    fontSize: 15,
    color: "#f8fefe",
    marginBottom: 8,
    marginLeft: 50,
  },
    faqAnswersSmallScreen: {
    fontSize: 15,
    color: "#f8fefe",
    marginBottom: 8,
    marginLeft: 19,
  },
  pricingNextLine: {
    fontSize: 15,
    color: "#f8fefe",
    marginBottom: 5,
    marginLeft: 50,
  },
    pricingNextLineSmallScreen: {
    fontSize: 15,
    color: "#f8fefe",
    marginBottom: 5,
    marginLeft: 20,
  },
});
