import { StyleSheet } from "react-native";

export const personalStyles = StyleSheet.create({
  header: {
    width: "75%",
    alignSelf: "center",
    padding: 15,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: "#23CFBB",
  },
  headerOpactiy: {
    borderRadius: 15,
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#080e19",
    opacity: 0.5,
  },
  TitleText: {
    fontSize: 18,
    color: "#f8fefe",
    fontWeight: "400",
    marginBottom: 15,
    width: "70%",
    alignSelf: "center",
  },
  findView: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    marginTop: "1%",
    justifyContent: "space-evenly",
  },
  underLine: {
    width: "30%",
    height: 2,
    backgroundColor: "white",
    opacity: 0.5,
  },
  courseButtonView: {
    flexDirection: "row",
    width: "50%",
    alignSelf: "center",
    justifyContent: "space-evenly",
    marginTop: 15,
  },
  personalTutor: {
    backgroundColor: "#23CFBB",
    height: 60,
    width: "45%",
    borderRadius: 6,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    margin: 10,
  },
  buttonText: {
    fontSize: 20,
    color: "#080e19",
    width: "50%",
    alignItems: "center",
  },
  button2Text: {
    fontSize: 20,
    color: "#080e19",
    width: "75%",
    alignItems: "center",
  },
  courseView: {
    width: "55%",
    alignSelf: "center",
    padding: 15,
    borderRadius: 15,
    borderWidth: 2,
    marginTop: -7,
    borderColor: "#23CFBB",
  },
  detailsView: {
    marginTop: 15,
    width: "20%",
    alignSelf: "center",
    justifyContent: "space-around",
    flexDirection: "row",
  },
  detailsButton1: {
    backgroundColor: "#C2F5EF",
    height: 60,
    width: "45%",
    borderRadius: 6,
    justifyContent: "center",
    alignItems: "center",
    margin: 10,
  },
  buttonCourseText: {
    fontSize: 20,
    color: "080e19",
    width: "80%",
    justifyContent: "center",
  },
  buttonCourseText2: {
    fontSize: 20,
    color: "#080e19",
    width: "35%",
    justifyContent: "center",
  },
  mainOpacity: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "black",
    opacity: 0.3,
  },
  findDetails: {
    fontSize: 20,
    color: "#f8fefe",
    fontWeight: "400",
  },
});
