import { StyleSheet } from "react-native";

export const courseStyles = StyleSheet.create({
  mainContainer: {
    width: "100%",
    backgroundColor: "#080e19",
    height: "55%",
    marginTop: "-2%",
  },
    mainContainerMobile: {
    width: "100%",
    backgroundColor: "#080e19",
    height: "79%",
  },
  textboxOne: {
    width: "50%",
    alignSelf: "center",
    alignItems:"center",
    marginTop: 30,
  },
  title: {
    alignSelf: "center",
    color: "#23CFBB",
    fontSize: 20,
    fontWeight: "500",
  },
  subtitle: {
    width: "90%",
    alignSelf: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  subtext: {
    alignSelf: "center",
    color: "#FFFFFF",
    fontWeight: "bold",
    fontSize: 40,
  },
  footerText: {
    marginTop: 10,
    alignSelf: "center",
    color: "#B1BABA",
    fontSize: 20,
    alignItems: "center",
  },
  secondaryView: {
    width: "100%",
    backgroundColor: "#080e19",
    height: "100%",
  },
  courseBox: {
    borderWidth: 1.5,
    borderColor: "#656969",
    marginTop: 30,
    width: "90%",
    alignSelf: "center",
    height: "90%",
    borderRadius: 20,
    flexDirection: "row",
  },
  courseTile: {
    flex: 0.4,
    backgroundColor: "#0F1727",
    marginTop: "3%",
    marginLeft: "3%",
    marginRight: "3%",
    width: "10%",
    height: "80%",
    padding: 20,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#06443e",
    justifyContent: "space-around",
  },
  courseTileMobile: {
    backgroundColor: "#0F1727",
    marginTop: "3%",
    // marginLeft: "3%",
    marginRight: "3%",
    width: "100%",
    height: "30%",
    padding: 20,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#06443e",
    justifyContent: "space-around",
  },
  tView: { width: "90%", height: "100%", paddingBottom: 15, borderRadius: 15 },
  iconMobile: {
    color: "#23CFBB",
    height: "1%",
    width: "5%",
    alignSelf: "flex-start",
    marginLeft: "5%",
    marginTop: "5%",
    backgroundColor: "#05423A",
    padding: 8,
    borderRadius: 10,
  },
  icon: {
    color: "#23CFBB",
    height: "20%",
    width: "10%",
    alignSelf: "flex-start",
    marginLeft: "5%",
    marginTop: "5%",
    backgroundColor: "#05423A",
    padding: 8,
    borderRadius: 10,
  },

  iconOne: {
    color: "#23CFBB",
    height: 55,
    width: "10%",
    alignSelf: "flex-start",
    marginLeft: "5%",
    marginTop: "5%",
    backgroundColor: "#06443e",
    padding: 8,
    borderRadius: 10,
  },
  courseTitle: {
    color: "white",
    fontSize: 25,
    fontWeight: "600",
    marginTop: "3%",
    alignSelf: "flex-start",
    marginLeft: "5%",
  },
  courseDesc: {
    color: "white",
    fontSize: 20,
    fontWeight: "400",
    marginTop: "5%",
    lineHeight: 30,
    marginLeft: "5%",
  },
});
